Restored old dist

diff --git a/grakn-dist/src/grakn b/grakn-dist/src/grakn
--- a/grakn-dist/src/grakn
+++ b/grakn-dist/src/grakn
@@ -34,74 +34,54 @@
 # ================================================
 
 # ================================================
+# global variables
+# ================================================
+
+# globals
+WAIT_INTERVAL_S=2
+
+# Grakn globals
+# TODO: clean up
+if [ -z "${GRAKN_HOME}" ]; then
+    [[ $(readlink $0) ]] && path=$(readlink $0) || path=$0
+    GRAKN_HOME=$(cd "$(dirname "${path}")" && pwd -P)
+    GRAKN_CONFIG="${GRAKN_HOME}/conf/grakn.properties"
+    GRAKN_PID=/tmp/grakn.pid
+    GRAKN_STARTUP_TIMEOUT_S=120
+fi
+
+# Storage globals
+STORAGE_PID=/tmp/grakn-storage.pid
+STORAGE_STARTUP_TIMEOUT_S=60
+
+# Queue globals
+QUEUE_STARTUP_TIMEOUT_S=10
+
+# ================================================
 # common helper functions
 # ================================================
 update_classpath_global_var() {
   # Define CLASSPATH, exclude slf4j as we use logback
-  for jar in ./services/lib/*.jar; do
+  for jar in "${GRAKN_HOME}"/services/lib/*.jar; do
       if [[ $jar != *slf4j-log4j12* ]] ; then
           CLASSPATH="$CLASSPATH":"$jar"
       fi
   done
 
   # Add path containing grakn.properties and logback.xml
-  CLASSPATH="$CLASSPATH":./conf
-  CLASSPATH="$CLASSPATH":./services/grakn
-}
-
-wait_until_terminated() {
-  while kill -0 "$1" 2>/dev/null; do
-    echo -n "." # output some sort of "progress bar"
-    sleep $WAIT_INTERVAL_S
-  done
-}
-
-print_status_message() {
-  if [ $1 -eq 0 ] ; then
-      echo "SUCCESS"
-  else
-      echo "FAILED!"
-  fi
-}
-
-print_failure_diagnostics() {
-  echo "======== Failure Diagnostics ========"
-  echo "Grakn pid = '`cat $GRAKN_PID`' (from $GRAKN_PID), '`grakn_get_pid_by_ps_ef`' (from ps -ef)"
-  echo "Queue pid = '`cat $QUEUE_PID`' (from $QUEUE_PID), '`queue_get_pid_by_ps_ef`' (from ps -ef)"
-  echo "Storage pid = '`cat $STORAGE_PID`' (from $STORAGE_PID)"
-}
-
-wait_until_terminated() {
-  while kill -0 "$1" 2>/dev/null; do
-    echo -n "." # output some sort of "progress bar"
-    sleep $WAIT_INTERVAL_S
-  done
-}
-
-print_status_message() {
-  if [ $1 -eq 0 ] ; then
-      echo "SUCCESS"
-  else
-      echo "FAILED!"
-  fi
-}
-
-print_failure_diagnostics() {
-  echo "======== Failure Diagnostics ========"
-  echo "Grakn pid = '`cat $GRAKN_PID`' (from $GRAKN_PID), '`grakn_get_pid_by_ps_ef`' (from ps -ef)"
-  echo "Queue pid = '`cat $QUEUE_PID`' (from $QUEUE_PID), '`queue_get_pid_by_ps_ef`' (from ps -ef)"
-  echo "Storage pid = '`cat $STORAGE_PID`' (from $STORAGE_PID)"
+  CLASSPATH="$CLASSPATH":"${GRAKN_HOME}"/conf
+  CLASSPATH="$CLASSPATH":"${GRAKN_HOME}"/services/grakn
 }
 
 # ================================================
 # storage helper functions
 # ================================================
 storage_start_process() {
-  ./services/cassandra/cassandra -p $STORAGE_PID > /dev/null 2>&1
+  "${GRAKN_HOME}"/services/cassandra/cassandra -p $STORAGE_PID > /dev/null 2>&1
   return $?
 }
 
-storage_check_if_running_by_pidfile() {
+storage_check_if_running() {
   local status=
   if [ -e $STORAGE_PID ] && ps -p `cat $STORAGE_PID` > /dev/null ; then
     status=0 # storage running
@@ -119,7 +99,7 @@ storage_wait_until_ready() {
   while [ $now_s -le $stop_s ]; do
       echo -n "."
       # The \r\n deletion bit is necessary for Cygwin compatibility
-      status_thrift=`./services/cassandra/nodetool statusthrift 2>/dev/null | tr -d '\n\r'`
+      status_thrift=`"${GRAKN_HOME}"/services/cassandra/nodetool statusthrift 2>/dev/null | tr -d '\n\r'`
       if [ $? -eq 0 -a 'running' = "$status_thrift" ]; then
           return 0
       fi
@@ -131,7 +111,7 @@ storage_wait_until_ready() {
 }
 
 storage_start_and_wait_until_ready() {
-  storage_check_if_running_by_pidfile
+  storage_check_if_running
   is_storage_running=$?
 
   if [ $is_storage_running -eq 0 ]; then
@@ -154,20 +134,27 @@ storage_start_and_wait_until_ready() {
       status=1
     fi
 
-    print_status_message ${status}
+    if [ $status -eq 0 ]; then
+      echo "SUCCESS"
+    else
+      echo "FAILED!"
+    fi
+
     return $status
   fi
 }
 
-storage_stop_and_wait_until_terminated() {
+storage_stop_process() {
   echo -n "Stopping Storage..."
-  storage_check_if_running_by_pidfile
+  storage_check_if_running
   local is_storage_running=$?
   if [[ $is_storage_running -eq 0 ]]; then
     if [[ -e $STORAGE_PID ]]; then
       pid=`cat $STORAGE_PID`
       kill "$pid"
-      wait_until_terminated $pid
+      while kill -0 "$pid" 2>/dev/null; do
+          sleep 0.5
+      done
       echo "SUCCESS"
       return 0
     else
@@ -265,17 +252,14 @@ queue_start_process() {
   fi
 
   local status=$?
+  popd > /dev/null
 
   return $status
 }
 
-queue_get_pid_by_ps_ef() {
-  ps -ef | grep 'redis-server' | grep -v grep | awk '{print $2}'
-}
-
-queue_check_if_running_by_ps_ef() {
+queue_check_if_running() {
   local status=
-  local count_running_queue_process=`queue_get_pid_by_ps_ef | wc -l`
+  local count_running_queue_process=`ps -ef | grep 'redis-server' | grep -v grep | awk '{ print $2}' | wc -l`
   if [ $count_running_queue_process -gt 0 ] ; then
     status=0 # queue running
   else
@@ -290,7 +274,7 @@ queue_wait_until_ready() {
 
   while [ $now_s -le $stop_s ]; do
       echo -n "." # output some sort of "progress bar"
-      queue_check_if_running_by_ps_ef
+      queue_check_if_running
       local is_queue_running=$?
       if [ $is_queue_running -eq 0 ] ; then
           return 0
@@ -303,7 +287,7 @@ queue_wait_until_ready() {
 }
 
 queue_start_and_wait_until_ready() {
-  queue_check_if_running_by_ps_ef
+  queue_check_if_running
   is_queue_running=$?
 
   if [ $is_queue_running -eq 0 ]; then
@@ -321,19 +305,20 @@ queue_start_and_wait_until_ready() {
       # exec queue bin successful. now wait until ready
       queue_wait_until_ready
       status=$?
+      echo "SUCCESS"
     else
       # exec queue bin failed
       status=1
+      echo "FAILED!"
     fi
 
-    print_status_message ${status}
     return $status
   fi
 }
 
-queue_stop_and_wait_until_terminated() {
+queue_stop_process() {
   echo -n "Stopping Queue..."
-  queue_check_if_running_by_ps_ef
+  queue_check_if_running
   local is_queue_running=$?
   if [[ $is_queue_running -eq 0 ]]; then
     local queue_bin=
@@ -342,12 +327,13 @@ queue_stop_and_wait_until_terminated() {
     elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
         queue_bin="redis-cli-linux"
     fi
-
-    local pid=`cat $QUEUE_PID`
-    ./services/redis/$queue_bin shutdown
-    wait_until_terminated $pid
+    "${GRAKN_HOME}/services/redis/"$queue_bin shutdown
     local status=$?
-    print_status_message ${status}
+    if [ $status -eq 0 ] ; then
+      echo "SUCCESS"
+    else
+      echo "FAILED!"
+    fi
   else
     echo "NOT RUNNING"
   fi
@@ -363,7 +349,7 @@ queue_wipe_all_data() {
       queue_bin="redis-cli-linux"
   fi
 
-  ./services/redis/$queue_bin flushall
+  "${GRAKN_HOME}/services/redis/"$queue_bin flushall
 }
 
 # ================================================
@@ -371,19 +357,15 @@ queue_wipe_all_data() {
 # ================================================
 grakn_start_process() {
   local status=
-  java -cp "${CLASSPATH}" -Dgrakn.dir="./services" -Dgrakn.conf="${GRAKN_CONFIG}" \
+  java -cp "${CLASSPATH}" -Dgrakn.dir="${GRAKN_HOME}/services" -Dgrakn.conf="${GRAKN_CONFIG}" \
     ai.grakn.engine.Grakn > /dev/null 2>&1 &
   status=$?
-  pid=`grakn_get_pid_by_ps_ef`
+  pid=`ps -ef | grep Grakn | grep -v grep | awk '{ print $2}'`
   echo $pid > "${GRAKN_PID}"
   return $status
 }
 
-grakn_get_pid_by_ps_ef() {
-  ps -ef | grep Grakn | grep -v grep | awk '{ print $2}'
-}
-
-grakn_check_if_running_by_pidfile() {
+grakn_check_if_running() {
   if [ -e "$GRAKN_PID" ] && ps -p `cat $GRAKN_PID` > /dev/null ; then
     return 0
   else
@@ -392,10 +374,10 @@ grakn_check_if_running_by_pidfile() {
 }
 
 grakn_check_if_ready() {
-  local host=`cat ./conf/grakn.properties| grep server.host | awk -F "=" '{print $2}'`
-  local port=`cat ./conf/grakn.properties| grep server.port | awk -F "=" '{print $2}'`
+  local host=`cat "${GRAKN_HOME}"/conf/grakn.properties| grep server.host | awk -F "=" '{print $2}'`
+  local port=`cat "${GRAKN_HOME}"/conf/grakn.properties| grep server.port | awk -F "=" '{print $2}'`
   curl $host:$port/configuration > /dev/null 2>&1
-  return $? # curl would return 0 upon a successful response or nonzero otherwise
+  return $?
 }
 
 grakn_wait_until_ready() {
@@ -417,7 +399,7 @@ grakn_wait_until_ready() {
 }
 
 grakn_start_and_wait_until_ready() {
-  grakn_check_if_running_by_pidfile
+  grakn_check_if_running
   is_grakn_running=$?
 
   if [ $is_grakn_running -eq 0 ]; then
@@ -435,70 +417,57 @@ grakn_start_and_wait_until_ready() {
       # exec grakn bin successful. now wait until ready
       grakn_wait_until_ready
       status=$?
+      echo "SUCCESS"
     else
       # exec grakn bin failed
       status=1
+      echo "FAILED!"
     fi
 
-    print_status_message ${status}
     return $status
   fi
 }
 
-grakn_stop_and_wait_until_terminated() {
+grakn_stop_process() {
   echo -n "Stopping Grakn..."
-  local status=
-  grakn_check_if_running_by_pidfile
+  grakn_check_if_running
   local is_grakn_running=$?
   if [[ $is_grakn_running -eq 0 ]]; then
     if [[ -e "$GRAKN_PID" ]]; then
-      local pid=`cat "$GRAKN_PID"`
-      kill "$pid"
-      local status_kill=$?
-      if [ $status_kill -eq 0 ]; then
-        wait_until_terminated $pid
-        local status_wait_until_terminated=$?
-        if [ $status_wait_until_terminated -eq 0 ]; then
-          rm "$GRAKN_PID"
-          local status_delete_pid_after_termination=$?
-          if [ $status_delete_pid_after_termination -eq 0 ]; then
-            status=0
-          else
-            status=1 # unable to delete pid file after grakn is terminated
-          fi
-        else
-          status=1 # wait failed for some reason
-        fi
+      kill `cat $GRAKN_PID`
+      status_kill=$?
+      rm $GRAKN_PID
+      if [ $status_kill -eq 0 ] ; then
+        echo "SUCCESS"
       else
-        status=1 # unable to kill for some reason
+        echo "FAILED!" # unable to kill
       fi
+      return $status_kill
     else
-      status=1 # unable to find PID file
+      echo "FAILED!" # unable to find PID file
+      return 1
     fi
-    print_status_message ${status}
-    return $status
   else
     echo "NOT RUNNING"
-    return 0
   fi
 }
 
 grakn_wipe_all_data() {
-  rm -r ./logs
-  mkdir ./logs
+  rm -r "${GRAKN_HOME}"/logs
+  mkdir "${GRAKN_HOME}"/logs
 }
 
 # ================================================
 # command line case statement helpers
 # ================================================
 cli_case_grakn_server_stop_all() {
-  grakn_stop_and_wait_until_terminated
+  grakn_stop_process
   status_grakn=$?
 
-  queue_stop_and_wait_until_terminated
+  queue_stop_process
   status_queue=$?
 
-  storage_stop_and_wait_until_terminated
+  storage_stop_process
   status_storage=$?
 
   if [ $status_grakn -eq 0 ] && [ $status_queue -eq 0 ] && [ $status_storage -eq 0 ] ; then
@@ -574,14 +543,14 @@ Tips:
 "
 }
 cli_case_grakn_server_status() {
-  storage_check_if_running_by_pidfile
+  storage_check_if_running
   if [ $? -eq 0 ] ; then
     echo "Storage: RUNNING"
   else
     echo "Storage: NOT RUNNING"
   fi
 
-  queue_check_if_running_by_ps_ef
+  queue_check_if_running
   if [ $? -eq 0 ] ; then
     echo "Queue: RUNNING"
   else
@@ -594,19 +563,13 @@ cli_case_grakn_server_status() {
   else
     echo "Grakn: NOT RUNNING"
   fi
-
-  case $1 in
-    --verbose)
-      print_failure_diagnostics
-    ;;
-  esac
 }
 
 cli_case_grakn_server_clean() {
-  storage_check_if_running_by_pidfile
+  storage_check_if_running
   local is_storage_running=$?
 
-  queue_check_if_running_by_ps_ef
+  queue_check_if_running
   local is_queue_running=$?
 
   grakn_check_if_ready
@@ -628,7 +591,7 @@ cli_case_grakn_server_clean() {
 
     queue_start_and_wait_until_ready
     queue_wipe_all_data
-    queue_stop_and_wait_until_terminated
+    queue_stop_process
     echo "Cleaning Queue...SUCCESS"
 
     echo -n "Cleaning Grakn..."
@@ -682,7 +645,7 @@ cli_case_grakn_cluster_status() {
 }
 
 cli_case_grakn_version() {
-  java -cp ${CLASSPATH} -Dgrakn.dir="./services" ai.grakn.graql.GraqlShell --version
+  java -cp ${CLASSPATH} -Dgrakn.dir="${GRAKN_HOME}/services" ai.grakn.graql.GraqlShell --version
 }
 
 cli_case_grakn_help() {
@@ -713,8 +676,6 @@ cli_case_grakn_server_start() {
       else
         # failure detected. attempt to terminate every component gracefully
         echo "Unable to start Grakn. Please run 'grakn server status' or check the logs located under 'logs' directory."
-        print_failure_diagnostics
-
         exit 1
       fi
     ;;
@@ -727,8 +688,6 @@ cli_case_grakn_server_start() {
       else
         # failure detected. attempt to terminate every component gracefully
         echo "Unable to start Queue. Please run 'grakn server status' or check the logs located under 'logs' directory."
-        print_failure_diagnostics
-
         exit 1
       fi
     ;;
@@ -741,8 +700,6 @@ cli_case_grakn_server_start() {
       else
         # failure detected. attempt to terminate every component gracefully
         echo "Unable to start Storage. Please run 'grakn server status' or check the logs located under 'logs' directory."
-        print_failure_diagnostics
-
         exit 1
       fi
     ;;
@@ -755,8 +712,6 @@ cli_case_grakn_server_start() {
       else
         # failure detected. attempt to terminate every component gracefully
         echo "Unable to start Grakn. Please run 'grakn server status' or check the logs located under 'logs' directory."
-        print_failure_diagnostics
-
         exit 1
       fi
     ;;
@@ -764,62 +719,19 @@ cli_case_grakn_server_start() {
 }
 
 cli_case_grakn_server_stop() {
+  # TODO: handle if graceful termination failed and log failures
   case $1 in
     grakn)
-      grakn_stop_and_wait_until_terminated
-      status=$?
-      if [ $status -eq 0 ] ; then
-        # do nothing
-        exit 0
-      else
-        # failure detected. attempt to terminate every component gracefully
-        echo "Unable to stop Grakn. Please run 'grakn server status' or check the logs located under 'logs' directory."
-        print_failure_diagnostics
-
-        exit 1
-      fi
+      grakn_stop_process
     ;;
     queue)
-      queue_stop_and_wait_until_terminated
-      status=$?
-      if [ $status -eq 0 ] ; then
-        # do nothing
-        exit 0
-      else
-        # failure detected. attempt to terminate every component gracefully
-        echo "Unable to stop Queue. Please run 'grakn server status' or check the logs located under 'logs' directory."
-        print_failure_diagnostics
-
-        exit 1
-      fi
+      queue_stop_process
     ;;
     storage)
-      storage_stop_and_wait_until_terminated
-      status=$?
-      if [ $status -eq 0 ] ; then
-        # do nothing
-        exit 0
-      else
-        # failure detected. attempt to terminate every component gracefully
-        echo "Unable to stop Storage. Please run 'grakn server status' or check the logs located under 'logs' directory."
-        print_failure_diagnostics
-
-        exit 1
-      fi
+      storage_stop_process
     ;;
     *)
       cli_case_grakn_server_stop_all
-      status=$?
-      if [ $status -eq 0 ] ; then
-        # do nothing
-        exit 0
-      else
-        # failure detected. attempt to terminate every component gracefully
-        echo "Unable to stop Storage. Please run 'grakn server status' or check the logs located under 'logs' directory."
-        print_failure_diagnostics
-
-        exit 1
-      fi
     ;;
   esac
 }
@@ -839,36 +751,12 @@ handle_ctrl_c() {
 # =============================================
 print_grakn_logo() {
   # cat ASCII logo, or fail silently if it's somehow missing
-  cat ./services/grakn/grakn-ascii.txt 2> /dev/null
+  cat "${GRAKN_HOME}"/services/grakn/grakn-ascii.txt 2> /dev/null
 }
 
 # =============================================
 # main routine
 # =============================================
-
-# Common global variables
-WAIT_INTERVAL_S=2
-
-# Grakn global variables
-# TODO: clean up
-if [ -z "${GRAKN_HOME}" ]; then
-    [[ $(readlink $0) ]] && path=$(readlink $0) || path=$0
-    GRAKN_HOME=$(cd "$(dirname "${path}")" && pwd -P)
-fi
-
-GRAKN_CONFIG="../conf/grakn.properties"
-GRAKN_PID=/tmp/grakn.pid
-GRAKN_STARTUP_TIMEOUT_S=120
-
-# Storage global variables
-STORAGE_PID=/tmp/grakn-storage.pid
-STORAGE_STARTUP_TIMEOUT_S=60
-
-# Queue global variables
-QUEUE_STARTUP_TIMEOUT_S=10
-QUEUE_PID=/tmp/grakn-queue.pid
-
-pushd "$GRAKN_HOME" > /dev/null
 
 update_classpath_global_var
 
@@ -917,5 +805,3 @@ case "$1" in
     cli_case_grakn_help
   ;;
 esac
-
-popd > /dev/null
